language: node_js
node_js: stable
sudo: required
dist: trusty

cache:
  directories:
    - node_modules
    - "$HOME/.cache/bower"

script: 'true'

install:
  - npm install -g bower polymer-cli
  - npm install
  - bower install

after_success:
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      bash gh-pages.sh;
    fi
